name: Auto-enable Trivy SCA for new repos

on:
  repository:
    types: [created]

jobs:
  enable-trivy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout .github repo
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Authenticate GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth status

      - name: Copy Trivy workflow into new repo
        env:
          NEW_REPO: ${{ github.event.repository.full_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo clone "$NEW_REPO"
          mkdir -p "$(basename $NEW_REPO)/.github/workflows"
          cp .github/workflows/trivy-sca.yml "$(basename $NEW_REPO)/.github/workflows/trivy-sca.yml"
          cd "$(basename $NEW_REPO)"

          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .github/workflows/trivy-sca.yml
          git commit -m "Enable Trivy SCA scan"
          git push

